name: ci

on:
  push:
    branches-ignore:
      - '*.*.*'

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.8.5'
        architecture: 'x64'

    - run: |
        make setup-poetry
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH

    - name: configure poetry
      run: poetry config virtualenvs.in-project true

    - run: make install

    - run: make lint

    - run: make check

    - run: make test # should be make cov
